name: Issue comment labler

on:
    issue_comment:
        types: [created,  edited]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        if: contains(github.event.comment.body, '/user-review')
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'user-review-needed/사용자리뷰-요청'